### ISSUE TITLE
New version on PyPI?

### ISSUE THREAD

**Issue by mghughes** [danilop/yas3fs#124]
Any chance of releasing a new version on PyPI soon?

On 2.3.2 (latest version on PyPI) we ran into an issue with cache purging (#104), which has been fixed on master by PR #116. It would be great to be able to install a version with this fix from PyPI :)

Thanks

**Comment by unv-annihilator** [comment]
+1, Working with version 2.3.2 from PIP and hitting the cache bug that has been fixed.

**Comment by unv-annihilator** [comment]
Hey @danilop, any possibility of an ETA on when a new version might be pushed to PyPi? Trying to gauge whether I should plan to pull from PIP or if it'd be better to just pull from GitHub for implementing. Currently using the version off PyPi but won't be able to continue using that version due to the Uploads Cache clearing bug.

**Comment by cyphrsonic** [comment]
We are also being affected by this issue when installed via PIP. A new version would be great.

**Comment by bitsofinfo** [comment]
@danilop ?
