### ISSUE TITLE
Performance overhead for cached files ?

### ISSUE THREAD

**Issue by trecloux** [danilop/yas3fs#86]
Hi,

Thanks for this great piece of software :)

I'm trying yas3fs to deploy a php app on multiple machines, the php files are stores on s3 and mounted with yas3fs. Unfortunately, for the moment the performances are very poor. 
Should I expect the performances for cached files to be close to a local file system ?
Here is my command line :  `yas3fs s3://.......  /mnt/www --topic ..... --new-queue --uid 33 --gid 33 --cache-path /mnt/cache/s3 --prefetch 

Thanks for your support.

**Comment by danilop** [comment]
After the files are cached, in my experience performance are still a little
bit slower than a local file system, due to the FUSE emulation layer. It is
a long time than I am not using the prefetch command - not sure it is
working 100% as expected, maybe the cache needs to be pre-warmed by normal
use or a "find . | cat > /dev/null".

**Comment by bitsofinfo** [comment]
No matter what you do, FUSE filesystem performance will always be slower than native. Cached reads through FUSE will still be slower than native filesystem reads. It all boils down to FUSE's block size limitation
